name: Continuous Integration

on:
  workflow_dispatch:
  # push:
  #   branches: [ "fe-test" ]
  # pull_request:
  #   branches: [ "fe-test" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.7

    - name: Create .secret.properties file
      run:
        echo "${{ env.secret_file }}" > "${{ env.save_path }}"
      env:
        secret_file: ${{ secrets.FILE_SECRET_PROPERTIES }}
        save_path: '.secret.properties'
    
    - name: Set up JDK 17 # Gradle 8 requires java 17
      uses: actions/setup-java@v4.2.2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run Android Lint
      run: ./gradlew lint

    # - name: Run ktlint
    #   run: ./gradlew ktlintCheck
      
    # - name: Clean Bulid
    #   run: ./gradlew build

    - name: Run Local Unit Test
      run: ./gradlew test
      
    - name: Run Instrumented Unit Test
      uses: ReactiveCircus/android-emulator-runner@v2.32.0
      with:
       api-level: 34
       target: default
       arch: arm64-v8a
       profile: Nexus 6
       script: ./gradlew connectedAndroidTest
