name: Continuous Integration

on:
  workflow_dispatch:
  # push:
  #   branches: [ "fe-test" ]
  # pull_request:
  #   branches: [ "fe-test" ]

# NOTE: gradlew --no-daemon and gradlew stop for actions/cache work (#454)

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-level: [30] # [29, 30, 34]
        target: [google_apis]

    steps:
    #region setup
    - uses: actions/checkout@v4.1.7

    - name: Create .secret.properties file
      run:
        echo "${{ env.secret_file }}" > "${{ env.save_path }}"
      env:
        secret_file: ${{ secrets.FILE_SECRET_PROPERTIES }}
        save_path: '.secret.properties'
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Set up JDK 17 # Gradle 8 requires java 17
      uses: actions/setup-java@v4.2.2
      with:
        java-version: '17'
        distribution: 'temurin'
        # cache: 'gradle' # Not working well
    
    - name: Gradle cache
      uses: gradle/actions/setup-gradle@v3
      with:
        build-scan-publish: true
        build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
        build-scan-terms-of-use-agree: "yes"
    #endregion setup


    - name: 1. Run Android Lint
      run: ./gradlew lint --no-daemon

    # TODO: detekt
      
    - name: 3. Run Local Unit Test
      run: ./gradlew test --no-daemon
      

    #region 4. Instrumented Unit Test
    - name: Enable KVM # Hardware acceleration for linux runner
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm

    - name: AVD cache
      uses: actions/cache@v4
      id: avd-cache
      with:
        path: |
          ~/.android/avd/*
          ~/.android/adb*
        key: avd-${{ matrix.api-level }}-${{ matrix.target }}

    - name: create AVD and generate snapshot for caching
      if: steps.avd-cache.outputs.cache-hit != 'true'
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ matrix.api-level }}
        target: ${{ matrix.target }}
        arch: x86_64 # arm64-v8a not available on linux x86 runner
        force-avd-creation: false
        emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        disable-animations: false
        script: echo "Generated AVD snapshot for caching."

    - name: 4. Run Instrumented Unit Test
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ matrix.api-level }}
        target: ${{ matrix.target }}
        arch: x86_64
        force-avd-creation: false
        emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        disable-animations: true
        script: ./gradlew connectedAndroidTest --no-daemon
    #endregion 4. Instrumented Unit Test

    
    # TODO: 5. Test Coverage

    # TODO: 6. Dependency Analysis Check

    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: app-build-outputs
        path: app/build/outputs
      if: ${{ always() }} # Even if previous steps failed
      

    # Report
    - name: Report
      uses: FlickerSoul/android-test-report-actions@v1.3.1
    # - name: Android Test Report
    #   uses: asadmansr/android-test-report-action@v1.2.0
      if: ${{ always() }} # Even if previous steps failed


    - name: Post AVD Cache (when failure) # Original post avd cache is not working if job fails
      uses: actions/cache/save@v3
      if: failure() && steps.avd-cache.outputs.cache-hit != 'true'
      with:
        path: |
          ~/.android/avd/*
          ~/.android/adb*
        key: avd-${{ matrix.api-level }}-${{ matrix.target }}
        
    - name: Stop Gradle # Is this needed?
      run: ./gradlew --stop
      if: ${{ always() }}
    
